### ISSUE TITLE
Fails to build because of missing icon

### ISSUE THREAD

**Issue by TingPing** [flathub/com.github.bajoja.indicator-kdeconnect#1]
```
Error loading desktop file: Failed to find icon: Failed to find icon kdeconnect
```

https://flathub.org/builds/#/builders/4/builds/1747

**Comment by Marukesu** [comment]
it's because the indicator uses the kdeconnect icon, but this don't come with her.
for now, i'm adding the kdeconnect to manifest but i can't export the org.kde.kdeconnectd.service because of the wrong prefix

**Comment by TingPing** [comment]
Just add the icons?
