### ISSUE TITLE
Mention that KDE Connect needs to be installed in app description

### ISSUE THREAD

**Issue by barthalion** [flathub/com.github.bajoja.indicator-kdeconnect#12]
As the app does not work without KDE Connect running at all, please include paragraph in appdata saying so.

**Comment by Marukesu** [comment]
Done.

**Comment by barthalion** [comment]
Build failed: https://flathub.org/builds/#/builders/32/builds/17789

Also log mentions `20.03.80`, is it a newer release?

**Comment by Marukesu** [comment]
> Build failed: https://flathub.org/builds/#/builders/32/builds/17789

Corrected.
> Also log mentions 20.03.80, is it a newer release?

It's seems like a pre-release
