### ISSUE TITLE
Needs a screenshot 

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.github.bajoja.indicator-kdeconnect#2]
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

**Comment by Marukesu** [comment]
but it's have a image in appdata
![screenshot from 2018-02-20 13-38-05](https://user-images.githubusercontent.com/21296444/36436642-a25b1aea-1643-11e8-8482-793261d2e071.png)

**Comment by nedrichards** [comment]
Indeed. Could be a caching issue for @LeandroStanger

**Comment by LeandroStanger** [comment]
Started working again
![captura de tela de 2018-02-20 15-54-55](https://user-images.githubusercontent.com/26097419/36443041-6cd0e6ee-1656-11e8-87dc-9fb9873330c7.png)
