### ISSUE TITLE
Please remove usages of `branch` property from manifests

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.github.bajoja.indicator-kdeconnect#20]
This will be blocked soon, this is a heads up for that

https://github.com/flathub/com.github.bajoja.indicator-kdeconnect/blob/490d6a675454c8b50d33dcddd5d767a5e84f44fb/com.github.bajoja.indicator-kdeconnect.json#L108

should be a commit only or a tag or tag+commit.

**Comment by hfiguiere** [comment]
this was fixed in commit cc54dd4b4259873aa97fc3b65450118051a7f449
