### ISSUE TITLE
Retrying to find KDE Connect DBus service

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.github.bajoja.indicator-kdeconnect#3]
** Message: KDEConnectManager.vala:30: retrying to find KDE Connect DBus service
** Message: KDEConnectManager.vala:30: retrying to find KDE Connect DBus service
grep: /app/etc/xdg/autostart/kdeconnectd.desktop: No such file or directory

** (indicator-kdeconnect:3): CRITICAL **: string_substring: assertion '_tmp12_ <= _tmp13_' failed

(indicator-kdeconnect:3): GLib-GIO-CRITICAL **: g_file_new_for_path: assertion 'path != NULL' failed

(indicator-kdeconnect:3): GLib-GIO-CRITICAL **: g_file_query_exists: assertion 'G_IS_FILE(file)' failed
** Message: KDEConnectManager.vala:30: retrying to find KDE Connect DBus service
** Message: KDEConnectManager.vala:30: retrying to find KDE Connect DBus service
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

![captura de tela de 2018-02-20 19-44-20](https://user-images.githubusercontent.com/26097419/36453519-0d580c9e-1677-11e8-8141-5eb636cbcd00.png)

**Comment by nedrichards** [comment]
Yep this is expected. The KDE connect service isn't included in the Endless base OS nor is it inside the flatpak so it can't be found.

Discussion on ways to make this clearer to users and be able to bundle it in a flatpak is here: https://github.com/flathub/flathub/issues/268
